---
title: "election_model"
author: "Nikola Nikolov"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(plotly)
library(data.table)
```

## First, we start by historic election data, going back 4-5 elections. 

```{r elections 2021}

party <- c("SPD", "CDU/CSU", "Greens", "FDP", "AfD", "Left")
percentage <- c(25.7, 24.1, 14.7, 11.4, 10.4, 4.9)


# Combine the vectors into a data.table
election_data_2021 <- data.table(Party = party, Percentage = percentage)
party_colors <- c("SPD" = "#E3000F", "CDU/CSU" = "#000000", "Greens" = "#64A12D", "FDP" = "#FFD100", "AfD" = "#009EE0", "Left" = "#E60012")
election_data_2021 <- election_data_2021[order( -Percentage)]
election_data_2021$Party <- factor(election_data_2021$Party, levels = election_data_2021$Party)
# Create the plot
p <- plot_ly(
  data = election_data_2021, 
  x = ~Party, 
  y = ~Percentage, 
  type = 'bar',
  marker = list(color = ~party_colors[Party])   # Apply color based on party
) %>%
  layout(
    title = "Election Results",
    xaxis = list(title = "Party"),
    yaxis = list(title = "Percentage of Votes")
  )

# View the data table
p
```

# Historic data

## 2017



```{r elections 2017, echo=FALSE}
party <- c("SPD", "CDU/CSU", "Greens", "FDP", "AfD", "Left")
percentage <- c(20.5, 32.9, 8.9, 10.7, 12.6, 9.2)


# Combine the vectors into a data.table
election_data_2017 <- data.table(Party = party, Percentage = percentage)

election_data_2017 <- election_data_2017[order( -Percentage)]
election_data_2017$Party <- factor(election_data_2017$Party, levels = election_data_2017$Party)
# Create the plot
p1 <- plot_ly(
  data = election_data_2017, 
  x = ~Party, 
  y = ~Percentage, 
  type = 'bar',
  marker = list(color = ~party_colors[Party])   # Apply color based on party
) %>%
  layout(
    title = "Election Results",
    xaxis = list(title = "Party"),
    yaxis = list(title = "Percentage of Votes")
  )

# View the data table
p1
```

## 2013

```{r elections 2013, echo=FALSE}
party <- c("SPD", "CDU/CSU", "Greens", "FDP", "AfD", "Left")
percentage <- c(25.7, 41.5, 8.4, 4.8, 1.9, 8.6)


# Combine the vectors into a data.table
election_data_2013 <- data.table(Party = party, Percentage = percentage)

election_data_2013 <- election_data_2013[order( -Percentage)]
election_data_2013$Party <- factor(election_data_2013$Party, levels = election_data_2013$Party)
# Create the plot
p1 <- plot_ly(
  data = election_data_2013, 
  x = ~Party, 
  y = ~Percentage, 
  type = 'bar',
  marker = list(color = ~party_colors[Party])   # Apply color based on party
) %>%
  layout(
    title = "Election Results 2013",
    xaxis = list(title = "Party"),
    yaxis = list(title = "Percentage of Votes")
  )

# View the data table
p1
```

## 2009

```{r elections 2009, echo=FALSE}
party <- c("SPD", "CDU/CSU", "Greens", "FDP", "Left")
percentage <- c(23.0, 33.8, 10.7, 14.6, 8.6)


# Combine the vectors into a data.table
election_data_2009 <- data.table(Party = party, Percentage = percentage)

election_data_2009 <- election_data_2009[order( -Percentage)]
election_data_2009$Party <- factor(election_data_2009$Party, levels = election_data_2009$Party)
# Create the plot
p1 <- plot_ly(
  data = election_data_2009, 
  x = ~Party, 
  y = ~Percentage, 
  type = 'bar',
  marker = list(color = ~party_colors[Party])   # Apply color based on party
) %>%
  layout(
    title = "Election Results 2009",
    xaxis = list(title = "Party"),
    yaxis = list(title = "Percentage of Votes")
  )

# View the data table
p1
```

## 2005

```{r elections 2005, echo=FALSE}
party <- c("SPD", "CDU/CSU", "Greens", "FDP", "Left")
percentage <- c(34.2, 35.2, 8.1, 9.8, 8.7)


# Combine the vectors into a data.table
election_data_2005 <- data.table(Party = party, Percentage = percentage)

election_data_2005 <- election_data_2005[order( -Percentage)]
election_data_2005$Party <- factor(election_data_2005$Party, levels = election_data_2005$Party)
# Create the plot
p1 <- plot_ly(
  data = election_data_2005, 
  x = ~Party, 
  y = ~Percentage, 
  type = 'bar',
  marker = list(color = ~party_colors[Party])   # Apply color based on party
) %>%
  layout(
    title = "Election Results 2005",
    xaxis = list(title = "Party"),
    yaxis = list(title = "Percentage of Votes")
  )

# View the data table
p1
```